project_name: uif
builds:
  - id: build_for_linux
    main: ./
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v1
      - linux_arm64
      - linux_arm_7
      - linux_mipsle

  - id: build_for_macos
    main: ./
    env:
      - CGO_ENABLED=1
    targets:
      # - darwin_amd64_v1
      - darwin_arm64

  - id: build_for_windows
    main: ./
    env:
      - CGO_ENABLED=0
    ldflags:
      - -H=windowsgui
    targets:
      - windows_amd64_v1
      # - windows_arm64

archives:
  - id: Compress Archives
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    strip_parent_binary_folder: true
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    files:
      - src: "./webs_dist/**"
        dst: "./webs/"

      - src: "./version/**"
        dst: "./version/"

      - src: "./cores/{{ .Os }}/{{ .Arch }}/**"
        dst: "./cores/"

      # - src: "./frp/{{ .Os }}/{{ .Arch }}/*/"
      #   dst: "./frp/"

      - src: "./uifd_dist/{{ .Os }}/{{ .Arch }}/**"
        dst: "./uifd/"

      - src: "./cache.db"
        dst: "./cache.db"

release:
  github:
    owner: UIforFreedom
    name: UIF
  name_template: "{{ .Version }}"
  # draft: true
  mode: replace

source:
  enabled: false
checksum:
  disable: true
